$ANSIBLE_VAULT;1.1;AES256
34313032303366623035623262663331303133356535346433373262303763376139306532633136
3535316363643538376235383631353063303565653433660a363863393733346338323133336565
35666137646161316236376435323464396264376537636165313530666534626465386235386233
6332356337376461330a643664653039386465653166343832396364346531613132663866323964
62633736343232386366626539353235633665376564643336613832303736656166313364366333
36666339313337323839356261303630363139323932656362626633363732636263646464633064
39633830346538313138393432653038326466623236313137383762316231653561633135386264
37386164623936346332613233376135386166636331333364663663393035623861336265363332
37623430636564386137363936333466646537643932626361386532346536613235343563633432
6562613137653736386664356134303234366330633464393039
