$ANSIBLE_VAULT;1.1;AES256
36663263643836623737336433613361323835356632656161656166366435653133623238343433
6436616363613539613031313162356235643261636432660a633835623233366532643134656335
39393337363738303264346261316264366438356332346163313233623632343961386163373539
3237653564393237300a383239343363623934626365636236383639316431613330303038326364
62336261633265363734656564393237373862303264346461636361303066663366306535303631
37646432613830613934663964616337613735646264303863316433316434343964633065316366
31643034613861313362343438336632346332663561323866383837386632386462326333313363
65313866646534623735656138373966363134353335316361653462626334346663363638386237
6265
